name: Check for broken links

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --no-progress
            --accept 200,206,429
            '*.html'
          fail: true